### ISSUE TITLE
[Bug]: flutter depends on temurin8-jdk, but it can't run on that version of JDK

### ISSUE THREAD

**Issue by dodumosu** [ScoopInstaller/Extras#10413]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

flutter

### Expected/Current Behaviour

flutter depends on temurin8-jdk, but actually running the flutter command to accept the Android SDK licenses fails on that JDK version.

### Steps to Reproduce

```console
install temurin8-jdk (without any other JDK/JRE), install flutter, then try to run `flutter doctor --android-licenses` (to accept the Android SDK licenses)

PS> scoop install temurin8-jdk
PS> scoop install flutter
PS> flutter doctor --android-licenses
```

### Possible Solution

Installing a newer JDK (i have temurin17-jdk installed personally) allows 

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
31469bc0a (HEAD -> master, origin/master, origin/HEAD) postman@10.9.0: Fix hash (Closes #10410)

'java' bucket:
53ffa7f8 (HEAD -> master, origin/master, origin/HEAD) temurin19-nightly-jdk: Update to version 19.0.2-7.0.202302020347

'main' bucket:
4694db89f (HEAD -> master, origin/master, origin/HEAD) keptn: Add version 1.1.0 (#4412)

'nerd-fonts' bucket:
ac2c7cb (HEAD -> master, origin/master, origin/HEAD) andika: Update to version 6.200

'versions' bucket:
14e96329b (HEAD -> master, origin/master, origin/HEAD) sharex-dev: Fix url (#974)
```

### Scoop Config

```console
last_update         aria2-enabled scoop_repo                              scoop_branch
-----------         ------------- ----------                              ------------
2/2/2023 8:56:03 PM          True https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.8
PSEdition                      Core
GitCommitId                    7.2.8
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by HUMORCE** [comment]
Please leave the full output of the installation.

**Comment by HUMORCE** [comment]
```
❯ scoop install temurin8-jdk
Installing 'temurin8-jdk' (8.0.362-9) [64bit] from java bucket
Loading OpenJDK8U-jdk_x64_windows_hotspot_8u362b09.zip from cache
Checking hash of OpenJDK8U-jdk_x64_windows_hotspot_8u362b09.zip ... ok.
Extracting OpenJDK8U-jdk_x64_windows_hotspot_8u362b09.zip ... done.
Linking ~\scoop\apps\temurin8-jdk\current => ~\scoop\apps\temurin8-jdk\8.0.362-9
'temurin8-jdk' (8.0.362-9) was installed successfully!

❯ scoop install flutter
Installing 'adb' (33.0.3) [64bit] from main bucket
platform-tools_r33.0.3-windows.zip (5.4 MB) [=============================================================================] 100%
Checking hash of platform-tools_r33.0.3-windows.zip ... ok.
Extracting platform-tools_r33.0.3-windows.zip ... done.
Linking ~\scoop\apps\adb\current => ~\scoop\apps\adb\33.0.3
Creating shim for 'adb'.
Creating shim for 'dmtracedump'.
Creating shim for 'etc1tool'.
Creating shim for 'fastboot'.
Creating shim for 'hprof-conv'.
'adb' (33.0.3) was installed successfully!
Installing 'android-sdk' (4333796) [64bit] from extras bucket
Loading sdk-tools-windows-4333796.zip from cache
Checking hash of sdk-tools-windows-4333796.zip ... ok.
Extracting sdk-tools-windows-4333796.zip ... done.
Linking ~\scoop\apps\android-sdk\current => ~\scoop\apps\android-sdk\4333796
Creating shim for 'proguard'.
Creating shim for 'proguardgui'.
Creating shim for 'retrace'.
Creating shim for 'emulator'.
Creating shim for 'emulator-check'.
Creating shim for 'mksdcard'.
Creating shim for 'monitor'.
Persisting .knownPackages
Persisting build-tools
Persisting cmdline-tools
Persisting emulator
Persisting extras
Persisting licenses
Persisting ndk
Persisting patcher
Persisting platforms
Persisting skiaparser
Persisting sources
Persisting system-images
Running post_install script...
Warning: File C:\Users\humorce\.android\repositories.cfg could not be loaded.
License android-sdk-license:            ] 10% Computing updates...
---------------------------------------
Terms and Conditions

This is the Android Software Development Kit License Agreement
...
January 16, 2019
---------------------------------------
Accept? (y/N): y
[=======================================] 100% Unzipping... cmdline-tools/lib/RE
'android-sdk' (4333796) was installed successfully!
Installing 'flutter' (3.7.1) [64bit] from extras bucket
Loading flutter_windows_3.7.1-stable.zip from cache
Checking hash of flutter_windows_3.7.1-stable.zip ... ok.
Loading flutter-dev-setup.ps1 from cache
Checking hash of flutter-dev-setup.ps1 ... ok.
Extracting flutter_windows_3.7.1-stable.zip ... done.
Linking ~\scoop\apps\flutter\current => ~\scoop\apps\flutter\3.7.1
Creating shim for 'flutter'.
Creating shim for 'flutter-dev-setup'.
Running post_install script...
No build-tools detected. Installing the latest version... (build-tools;33.0.1)
Warning: File C:\Users\humorce\.android\repositories.cfg could not be loaded.                                        ]
Available platforms:
[1] platforms;android-7
[2] platforms;android-8
[3] platforms;android-9
[4] platforms;android-10
[5] platforms;android-11
[6] platforms;android-12
[7] platforms;android-13
[8] platforms;android-14
[9] platforms;android-15
[10] platforms;android-16
[11] platforms;android-17
[12] platforms;android-18
[13] platforms;android-19
[14] platforms;android-20
[15] platforms;android-21
[16] platforms;android-22
[17] platforms;android-23
[18] platforms;android-24
[19] platforms;android-25
[20] platforms;android-26
[21] platforms;android-27
[22] platforms;android-28
[23] platforms;android-29
[24] platforms;android-30
[25] platforms;android-31
[26] platforms;android-32
[27] platforms;android-33
For a list of platforms and what they mean, see: https://developer.android.com/about/dashboards/
No platform detected. Please select a platform to install [Default: 27]:
Platform platforms;android-28 selected. Installing...
Warning: File C:\Users\humorce\.android\repositories.cfg could not be loaded.                                        ]
All required dependencies for Android Development are installed.
Some licenses need to be accepted before developing. It is recommended to do by running 'flutter doctor --android-licenses'.
Running "flutter pub get" in flutter_tools...Test                                                                    ]
Resolving dependencies in scoop\apps\flutter\current\packages\flutter_tools... (4.9s)
  _fe_analyzer_shared 50.0.0 (52.0.0 available)
  analyzer 5.2.0 (5.4.0 available)
  archive 3.3.2 (3.3.6 available)
  args 2.3.1 (2.3.2 available)
  built_value 8.4.2 (8.4.3 available)
  checked_yaml 2.0.1 (2.0.2 available)
  collection 1.17.0 (1.17.1 available)
  completion 1.0.0 (1.0.1 available)
  coverage 1.6.1 (1.6.2 available)
  dds 2.5.0 (2.7.4 available)
  dds_service_extensions 1.3.1 (1.3.2 available)
  devtools_shared 2.18.0 (2.20.1 available)
  dwds 16.0.2 (17.0.0 available)
  fixnum 1.0.1 (1.1.0 available)
  frontend_server_client 3.1.0 (3.2.0 available)
  intl 0.17.0 (0.18.0 available)
  io 1.0.3 (1.0.4 available)
  js 0.6.5 (0.6.7 available)
  json_annotation 4.7.0 (4.8.0 available)
  logging 1.1.0 (1.1.1 available)
  matcher 0.12.13 (0.12.14 available)
  meta 1.8.0 (1.9.0 available)
  mime 1.0.2 (1.0.4 available)
  multicast_dns 0.3.2+2 (0.3.2+3 available)
  native_stack_traces 0.5.2 (0.5.5 available)
  path 1.8.2 (1.8.3 available)
  sse 4.1.1 (4.1.2 available)
  test 1.22.0 (1.22.2 available)
  test_api 0.4.16 (0.4.18 available)
  test_core 0.4.20 (0.4.22 available)
  vm_service 9.4.0 (10.1.2 available)
  web_socket_channel 2.2.0 (2.3.0 available)
  webdriver 3.0.1 (3.0.2 available)
Got dependencies in scoop\apps\flutter\current\packages\flutter_tools!
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.22621.1105], locale en-US)
    ! Warning: `flutter` on your path resolves to C:\Users\humorce\scoop\shims\flutter, which is not inside your current Flutter SDK
      checkout at C:\Users\humorce\scoop\apps\flutter\current. Consider adding C:\Users\humorce\scoop\apps\flutter\current\bin to
      the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\humorce\scoop\apps\flutter\3.7.1\bin\cache\dart-sdk\bin\dart.exe, which is
      not inside your current Flutter SDK checkout at C:\Users\humorce\scoop\apps\flutter\current. Consider adding
      C:\Users\humorce\scoop\apps\flutter\current\bin to the front of your path.
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
[!] Android Studio (not installed)
[✓] VS Code (version 1.75.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

'flutter' (3.7.1) was installed successfully!
'flutter' suggests installing 'vscode'.

❯ $env:JAVA_HOME
C:\Users\humorce\scoop\apps\temurin8-jdk\current
```

Cannot reproduce. but `android-sdk` will not be installed correctly, under JDK11.

```
❯ scoop install android-sdk
Installing 'android-sdk' (4333796) [64bit] from extras bucket
Loading sdk-tools-windows-4333796.zip from cache
Checking hash of sdk-tools-windows-4333796.zip ... ok.
Extracting sdk-tools-windows-4333796.zip ... done.
Linking ~\scoop\apps\android-sdk\current => ~\scoop\apps\android-sdk\4333796
Creating shim for 'proguard'.
Creating shim for 'proguardgui'.
Creating shim for 'retrace'.
Creating shim for 'emulator'.
Creating shim for 'emulator-check'.
Creating shim for 'mksdcard'.
Creating shim for 'monitor'.
Persisting .knownPackages
Persisting build-tools
Persisting cmdline-tools
Persisting emulator
Persisting extras
Persisting licenses
Persisting ndk
Persisting patcher
Persisting platforms
Persisting skiaparser
Persisting sources
Persisting system-images
Running post_install script...
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
'android-sdk' (4333796) was installed successfully!

❯ $env:JAVA_HOME
C:\Users\humorce\scoop\apps\zulu11-jdk\current
```

---

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/prefs/AndroidLocationsProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
https://javaalmanac.io/bytecode/versions/

**Comment by NoDocCat** [comment]
Should depends on openjdk17 and android-clt, Now the dependency is wrong.

**Comment by HUMORCE** [comment]
I made some changes to this manifest based on the official documentation and it now no longer forces a specific JAVA, `extras/android-sdk` dependency. DETAILED: #11109

For Android developers, it is recommended to install `main/android-clt` instead of `extras/android-sdk`.

**Comment by pcdd-group** [comment]
So far it is still wrong, flutter-cn.json should not depend on ojdkbuild8, flutter 3.19.2 is incompatible with gradle7
