### ISSUE TITLE
Github Desktop is not installed properly

### ISSUE THREAD

**Issue by andrewsav-bt** [ScoopInstaller/Extras#2071]
It seems when installing Github Desktop with scoop it is not installed properly. It gives the following error when run:

![GHd01](https://user-images.githubusercontent.com/27190911/56937005-b207fd80-6b4e-11e9-9a81-8e8f65774a27.png)

```
error: [ui] Error checking for updates
Error: The application is missing a dependency it needs to check and install updates. This is very, very bad.
    at Object.t.parseError (file:///C:/ProgramData/scoop/apps/github/1.6.5/resources/app/renderer.js:16:102797)
    at onAutoUpdaterError (file:///C:/ProgramData/scoop/apps/github/1.6.5/resources/app/renderer.js:10:33917)
    at CallbacksRegistry.apply (C:\ProgramData\scoop\apps\github\1.6.5\resources\electron.asar\common\api\callbacks-registry.js:47:25)
    at EventEmitter.ipcRenderer.on (C:\ProgramData\scoop\apps\github\1.6.5\resources\electron.asar\renderer\api\remote.js:285:21)
    at EventEmitter.emit (events.js:182:13)
```

Same error is given in the UI:
![GHd02](https://user-images.githubusercontent.com/27190911/56937103-132fd100-6b4f-11e9-9814-569c62462b79.png)

Even if the rest of the app seems to be functioning I do not really want the application to be missing a dependency, which is "very, very bad."

**Comment by superusercode** [comment]
I did not have this issue with the latest

**Comment by AndrewSav** [comment]
Still happening with the latest:

![Untitled](https://user-images.githubusercontent.com/658865/74615500-531b7f80-5186-11ea-8560-e09d1afebfce.png)

**Comment by pratikpc** [comment]
@AndrewSav @andrewsav-bt is this still an issue?

**Comment by AndrewSav** [comment]
I have no further information. If no one has fixed it it is reasonable to assume that it is still is.

**Comment by rashil2000** [comment]
Afaik, I saw this warning too when I used to use GitHub Desktop, but I didn't face any problems in the application itself. 

Reopen if the application misbehaves.
